export const INIT_SIDEBAR_DEVTOOL = "INIT_SIDEBAR_DEVTOOL";
export const TOGGLE_ITEM = "TOGGLE_ITEM";
export const TOGGLE_SUB_ITEM = "TOGGLE_SUB_ITEM";
export const STORED_CHANNEL_DATA = "STORED_CHANNEL_DATA";
export const STORED_NEW_CHANNEL_DATA = "STORED_NEW_CHANNEL_DATA";