
export const BOX_MESSAGE_GREEN = "background:green; color:white;";
export const BOX_MESSAGE_RED = "background:red; color:white;";

export const HEADER_SELECTOR_LOADED = "%c HEADER SELECTOR LOADED ";
export const HEADER_SELECTOR_NOT_LOADED = "%c HEADER SELECTOR LOADED ";

export const NAVBAR_SELECTOR_LOADED = "%c NAVBAR SELECTOR LOADED ";
export const NAVBAR_SELECTOR_NOT_LOADED = "%c NAVBAR SELECTOR LOADED ";

export const CENTRAL_SELECTOR_LOADED = "%c CENTRAL CONTENT SELECTOR LOADED ";
export const CENTRAL_SELECTOR_NOT_LOADED = "%c CENTRAL CONTENT SELECTOR LOADED ";

export const DEVTOOL_LOADED = "%c DEVTOOL SELECTOR LOADED ";
export const DEVTOOL_NOT_LOADED = "%c DEVTOOL SELECTOR NOT LOADED ";

export const FOOTER_SELECTOR_LOADED = "%c FOOTER SELECTOR LOADED ";
export const FOOTER_SELECTOR_NOT_LOADED = "%c FOOTER SELECTOR LOADED ";