export const INIT_APP = "INIT_APP";
export const INIT_EDITORIAL_CONTEXT = "INIT_EDITORIAL_CONTEXT";
export const STORED_EDITORIAL_CONTEXT = "STORED_EDITORIAL_CONTEXT";

export const NUMBER_ONE = 1;
export const NUMBER_TWO = 2;
export const NUMBER_THREE = 3;

